package com.netflixjess.model;

public enum Characteristics {

    DIVERTENTE, BIZZARRO, MALINCONICO, SUSPANCE, SPIAZZANTE, SCANDALOSO, SENSUALE,
    CRUDO, COMMOVENTE, INCANTEVOLE, OTTIMISTA, CUPO, EMOZIONANTE, ROMANTICO,
    DEMENZIALE, ANTICONFORMISTICO, ASSURDO, ESLPOSIVO, AZIONE, VIOLENTO

}
