package com.netflixjess.model;

public enum Genre {

    AZIONE, AVVENTURA, COMMEDIA, DOCUMENTARI, DRAMMA, FANTASY,
    FANTASCIENZA, FILM_INTERNAZIONALI, FILM_ITALIANI, FILM_BAMBINI,
    FILM_FAMIGLIE, ROMANTICO, HORROR , SERIE_TV
}
